/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author User
 */
public class OutPut extends javax.swing.JFrame {

    /**
     * Creates new form OutPut
     */
    private String currentUsername; // Add this at the top

    public OutPut(String userName,double idealWeight, double minWeight, double actualWeight) {
        initComponents();
            this.currentUsername = userName;

        System.out.println(idealWeight);
        
         double maxWeight = idealWeight * 1.1;
        
        String formatedIdealWeight = String.format("%.2f", idealWeight);
        String formatedMinWeight   = String.format("%.2f", minWeight);
        String formatedMaxWeight   = String.format("%.2f", maxWeight);
        String formateActualweight = String.format("%.2f", actualWeight);
        ActualWeight.setText(formateActualweight);
        IdealBodyWeight.setText(String.valueOf(formatedIdealWeight));
        IdealWeightrange.setText(formatedMinWeight+" - "+formatedMaxWeight);
        
        // Provide health tips based on weight status
        if (actualWeight < minWeight) {
            suggest.setText(" You are UNDERWEIGHT. Consider increasing your calorie intake with protein-rich foods.");
            System.out.println(" You are UNDERWEIGHT. Consider increasing your calorie intake with protein-rich foods.");
        } else if (actualWeight > maxWeight) {
            System.out.println(" You are OVERWEIGHT. A balanced diet and regular exercise can help you maintain a healthy weight.");
            suggest.setText("You are OVERWEIGHT. A balanced diet and regular exercise can help you maintain a healthy weight.");
        } else {
            System.out.println(" You are within the ideal weight range. Keep maintaining a healthy lifestyle!");
            suggest.setText("You are within the ideal weight range. Keep maintaining a healthy lifestyle!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IdealBodyWeight = new javax.swing.JTextField();
        IdealWeightrange = new javax.swing.JTextField();
        ActualWeight = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        suggest = new javax.swing.JTextArea();
        report = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Your Ideal Body Weight (IBW) ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(28, 50, 584, 41);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Your Ideal Weight Range");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(28, 160, 275, 41);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Your Actual Weight");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(28, 281, 275, 33);

        IdealBodyWeight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IdealBodyWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdealBodyWeightActionPerformed(evt);
            }
        });
        getContentPane().add(IdealBodyWeight);
        IdealBodyWeight.setBounds(28, 97, 236, 33);

        IdealWeightrange.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(IdealWeightrange);
        IdealWeightrange.setBounds(28, 207, 236, 34);

        ActualWeight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(ActualWeight);
        ActualWeight.setBounds(28, 320, 236, 36);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        suggest.setColumns(20);
        suggest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        suggest.setLineWrap(true);
        suggest.setRows(5);
        jScrollPane1.setViewportView(suggest);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(28, 374, 584, 53);

        report.setText("Report");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        getContentPane().add(report);
        report.setBounds(677, 50, 85, 23);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdealBodyWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdealBodyWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdealBodyWeightActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
        ReportWindow reportWin = new ReportWindow(currentUsername);
        reportWin.setVisible(true);
    }//GEN-LAST:event_reportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutPut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutPut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutPut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutPut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OutPut(12,45,45).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ActualWeight;
    private javax.swing.JTextField IdealBodyWeight;
    private javax.swing.JTextField IdealWeightrange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton report;
    private javax.swing.JTextArea suggest;
    // End of variables declaration//GEN-END:variables
}
